/*
 * This source file was generated by the Gradle 'init' task
 */
package knaefelda;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        System.out.println("Running game...");
        Game.main(args);
    }
}
