/*
 * This source file was generated by the Gradle 'init' task
 */
package knaefelda;

public class App {

    public static void main(String[] args) {
        System.out.println("Running game...");
        Game.main(args);
    }
    
}
